backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  # 1) Listado de locales para la home
  - name: "listado"
    label: "Listado (Home)"
    files:
      - label: "Locales"
        name: "locales"
        file: "data/locales.json"
        format: "json"
        fields:
          - label: "Locales"
            name: "locales"
            widget: "list"
            summary: "{{fields.nombre}} ({{fields.slug}})"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Rubro", name: "rubro", widget: "string", required: false }
              - { label: "Barrio", name: "barrio", widget: "string", required: false }
              - { label: "Logo URL", name: "logo", widget: "string", required: false }
              - { label: "Envío disponible", name: "envio", widget: "boolean", default: true }
              - { label: "Abierto ahora", name: "abierto", widget: "boolean", default: true }

  # 2) Locales – todo en un solo archivo por local: locales/<slug>/content.json
  - name: "locales"
    label: "Locales (contenido)"
    label_singular: "Local"
    folder: "locales"
    create: true
    extension: "json"
    format: "json"
    path: "{{fields.slug}}/content"
    identifier_field: "slug"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - label: "Ajustes"
        name: "ajustes"
        widget: "object"
        fields:
          - { label: "Nombre", name: "nombre", widget: "string" }
          - { label: "Subtítulo", name: "sub", widget: "string", required: false }
          - { label: "Logo URL", name: "logo", widget: "string", required: false }
          - { label: "WhatsApp (número)", name: "whatsapp", widget: "string" }
          - { label: "Costo de envío", name: "shipping", widget: "number", value_type: "int", default: 0 }
          - { label: "Analytics webhook (Apps Script)", name: "analytics_webhook", widget: "string", required: false }
          - { label: "Etiqueta de pestaña A", name: "tab_rotiseria", widget: "string", required: false, hint: "Ej: 🍕 Pizzas / 🔧 Herramientas" }
          - { label: "Etiqueta de pestaña B", name: "tab_bebidas", widget: "string", required: false, hint: "Ej: 🥤 Bebidas / 🧰 Accesorios" }
          - label: "Horarios"
            name: "horarios"
            widget: "object"
            fields:
              - label: "Rotisería"
                name: "rotiseria"
                widget: "object"
                fields:
                  - { label: "Días (0=Dom…6=Sáb)", name: "dias", widget: "list", field: {label: "día", name: "dia", widget: "number"} }
                  - label: "Rangos"
                    name: "rangos"
                    widget: "list"
                    fields:
                      - {label: "Desde", name: "desde", widget: "string"}
                      - {label: "Hasta", name: "hasta", widget: "string"}
              - label: "Bebidas"
                name: "bebidas"
                widget: "object"
                fields:
                  - { label: "Días (0=Dom…6=Sáb)", name: "dias", widget: "list", field: {label: "día", name: "dia", widget: "number"} }
                  - label: "Rangos"
                    name: "rangos"
                    widget: "list"
                    fields:
                      - {label: "Desde", name: "desde", widget: "string"}
                      - {label: "Hasta", name: "hasta", widget: "string"}
          - label: "Tema (opcional)"
            name: "theme"
            widget: "object"
            collapsed: true
            fields:
              - {label: "azul", name: "azul", widget: "string", required: false, hint: "Ej: #003366"}
              - {label: "amarillo", name: "amarillo", widget: "string", required: false}
              - {label: "bg", name: "bg", widget: "string", required: false}
              - {label: "text", name: "text", widget: "string", required: false}
      - label: "Productos"
        name: "productos"
        widget: "object"
        fields:
          - label: "Rotisería"
            name: "rotiseria"
            widget: "object"
            fields:
              - label: "Categorías"
                name: "categorias"
                widget: "list"
                fields:
                  - {label: "Categoría", name: "categoria", widget: "string"}
                  - label: "Productos"
                    name: "productos"
                    widget: "list"
                    fields:
                      - {label: "Nombre", name: "nombre", widget: "string"}
                      - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
                      - {label: "Descripción", name: "desc", widget: "string", required: false}
                      - {label: "Imagen URL", name: "img", widget: "string", required: false}
          - label: "Bebidas"
            name: "bebidas"
            widget: "object"
            fields:
              - label: "Categorías"
                name: "categorias"
                widget: "list"
                fields:
                  - {label: "Categoría", name: "categoria", widget: "string"}
                  - label: "Productos"
                    name: "productos"
                    widget: "list"
                    fields:
                      - {label: "Nombre", name: "nombre", widget: "string"}
                      - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
                      - {label: "Descripción", name: "desc", widget: "string", required: false}
                      - {label: "Imagen URL", name: "img", widget: "string", required: false}
      - label: "Promos"
        name: "promos"
        widget: "object"
        fields:
          - label: "Rotisería"
            name: "rotiseria"
            widget: "object"
            fields:
              - label: "Promos"
                name: "promos"
                widget: "list"
                fields:
                  - {label: "Nombre", name: "nombre", widget: "string"}
                  - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
                  - {label: "Precio original", name: "precio_original", widget: "number", value_type: "int", required: false}
                  - {label: "Tag", name: "tag", widget: "string", required: false}
                  - {label: "Descripción", name: "desc", widget: "string", required: false}
                  - {label: "Vigente hasta (YYYY-MM-DD)", name: "vigencia_hasta", widget: "string", required: false}
          - label: "Bebidas"
            name: "bebidas"
            widget: "object"
            fields:
              - label: "Promos"
                name: "promos"
                widget: "list"
                fields:
                  - {label: "Nombre", name: "nombre", widget: "string"}
                  - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
                  - {label: "Precio original", name: "precio_original", widget: "number", value_type: "int", required: false}
                  - {label: "Tag", name: "tag", widget: "string", required: false}
                  - {label: "Descripción", name: "desc", widget: "string", required: false}
                  - {label: "Vigente hasta (YYYY-MM-DD)", name: "vigencia_hasta", widget: "string", required: false}
