
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

local_backend: true

collections:
  - name: "listado"
    label: "Listado (Home)"
    files:
      - file: "data/locales.json"
        label: "Locales"
        name: "locales_file"
        fields:
          - label: "Locales"
            name: "locales"
            widget: "list"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Rubro", name: "rubro", widget: "string"}
              - {label: "Barrio", name: "barrio", widget: "string"}
              - {label: "Logo URL", name: "logo_url", widget: "string", required: false}

  - name: "catalogo"
    label: "Catálogo por local"
    folder: "data/negocios"
    create: true
    extension: "json"
    format: "json"
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Subtítulo", name: "subtitulo", widget: "string", required: false}
      - label: "Categorías"
        name: "categorias"
        widget: "list"
        fields:
          - {label: "Categoría", name: "categoria", widget: "string"}
          - label: "Productos"
            name: "productos"
            widget: "list"
            fields:
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Desc", name: "desc", widget: "string", required: false}
              - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
              - {label: "Imagen (URL)", name: "img", widget: "string", required: false}

  - name: "promos"
    label: "Promos"
    folder: "data/promos"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Slug del local", name: "slug_local", widget: "string"}
      - label: "Promos"
        name: "promos"
        widget: "list"
        fields:
          - {label: "Nombre", name: "nombre", widget: "string"}
          - {label: "Desc", name: "desc", widget: "string", required: false}
          - {label: "Precio", name: "precio", widget: "number", value_type: "int"}
          - {label: "Precio original", name: "precio_original", widget: "number", value_type: "int", required: false}
          - {label: "Etiqueta", name: "tag", widget: "string", required: false}
          - {label: "Vigencia hasta (YYYY-MM-DD)", name: "vigencia_hasta", widget: "string", required: false}

  - name: "ajustes"
    label: "Ajustes"
    files:
      - file: "data/ajustes.json"
        label: "Ajustes generales"
        name: "ajustes_file"
        fields:
          - {label: "WhatsApp (solo números)", name: "whatsapp", widget: "string"}
          - {label: "Costo de envío ($)", name: "shipping", widget: "number", value_type: "int"}
