backend:
  name: git-gateway
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "home"
    label: "Listado (Home)"
    files:
      - file: "locales/index.json"
        label: "Locales"
        name: "locales_index"
        fields:
          - label: "Locales"
            name: "locales"
            widget: "list"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Rubro", name: "rubro", widget: "string"}
              - {label: "Barrio", name: "barrio", widget: "string"}
              - {label: "Logo URL", name: "logo", widget: "string"}
              - label: "Secciones"
                name: "secciones"
                widget: "list"
                field: {label: "Sección", name: "section", widget: "string"}

  - name: "locales"
    label: "Locales"
    folder: "locales"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/content"
    extension: "json"
    format: "json"
    fields:
      - label: "Ajustes"
        name: "ajustes"
        widget: "object"
        fields:
          - {label: "Nombre", name: "nombre", widget: "string"}
          - {label: "Subtítulo", name: "sub", widget: "string", required: false}
          - {label: "Logo URL", name: "logo", widget: "string", required: false}
          - {label: "WhatsApp", name: "whatsapp", widget: "string", required: false}
          - {label: "Costo de envío", name: "shipping", widget: "number", value_type: "int", required: false}
          - label: "Secciones"
            name: "secciones"
            widget: "list"
            fields: [{label:"Nombre", name:"", widget:"string"}]
          - label: "Horarios"
            name: "horarios"
            widget: "object"
            fields:
              - label: "Sección 1"
                name: "sec1"
                widget: "object"
                required: false
                fields:
                  - {label:"Días (0=Dom)", name:"dias", widget:"list", field:{label:"día", name:"", widget:"number"}}
                  - label: "Rangos"
                    name: "rangos"
                    widget: "list"
                    fields:
                      - {label:"Desde", name:"desde", widget:"string"}
                      - {label:"Hasta", name:"hasta", widget:"string"}
              - label: "Sección 2"
                name: "sec2"
                widget: "object"
                required: false
                fields:
                  - {label:"Días (0=Dom)", name:"dias", widget:"list", field:{label:"día", name:"", widget:"number"}}
                  - label: "Rangos"
                    name: "rangos"
                    widget: "list"
                    fields:
                      - {label:"Desde", name:"desde", widget:"string"}
                      - {label:"Hasta", name:"hasta", widget:"string"}
          - label: "Cupones"
            name: "cupones"
            widget: "list"
            required: false
            fields:
              - {label:"Código", name:"code", widget:"string"}
              - {label:"Tipo", name:"type", widget:"select", options:["percent","amount","shipping_free"]}
              - {label:"Valor", name:"value", widget:"number", required:false}
              - {label:"Descripción", name:"desc", widget:"string", required:false}

      - label: "Sección 1"
        name: "sec1"
        widget: "object"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: "list"
            fields:
              - {label:"Categoría", name:"categoria", widget:"string"}
              - label: "Productos"
                name: "productos"
                widget: "list"
                fields:
                  - {label:"Nombre", name:"nombre", widget:"string"}
                  - {label:"Precio", name:"precio", widget:"number", value_type:"int"}
                  - {label:"Descripción", name:"desc", widget:"string", required:false}
                  - {label:"Imagen", name:"img", widget:"string", required:false}

      - label: "Sección 2"
        name: "sec2"
        widget: "object"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: "list"
            fields:
              - {label:"Categoría", name:"categoria", widget:"string"}
              - label: "Productos"
                name: "productos"
                widget: "list"
                fields:
                  - {label:"Nombre", name:"nombre", widget:"string"}
                  - {label:"Precio", name:"precio", widget:"number", value_type:"int"}
                  - {label:"Descripción", name:"desc", widget:"string", required:false}
                  - {label:"Imagen", name:"img", widget:"string", required:false}
