backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "listado"
    label: "Listado (Home)"
    editor: { preview: false }           # ⬅️ DESACTIVADO
    files:
      - file: "data/locales.json"
        name: "locales"
        label: "Locales"
        format: "json"
        editor: { preview: false }       # ⬅️ también acá
        fields:
          - label: "Locales"
            name: "locales"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Rubro", name: "rubro", widget: "string" }
              - { label: "Barrio", name: "barrio", widget: "string" }
              - { label: "Logo URL", name: "logo", widget: "string", required: false }

  - name: "catalogo"
    label: "Catálogo por local"
    folder: "data"
    extension: "json"
    create: false
    format: "json"
    editor: { preview: false }           # ⬅️ DESACTIVADO
    # (tus fields aquí)

  - name: "promos"
    label: "Promociones"
    folder: "data/promos"
    extension: "json"
    create: true
    format: "json"
    editor: { preview: false }           # ⬅️ DESACTIVADO
    # (tus fields aquí)

  - name: "ajustes"
    label: "Ajustes globales"
    editor: { preview: false }           # ⬅️ DESACTIVADO
    files:
      - file: "data/ajustes.json"
        name: "ajustes"
        label: "Ajustes"
        format: "json"
        editor: { preview: false }       # ⬅️ DESACTIVADO
        # (tus fields aquí)
