backend:
  name: git-gateway
  branch: main

logo_url: "/uploads/logo.png"
site_url: "/"
locale: "es"
custom_styles: "/admin/custom.css"

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "locales"
    label: "Locales (listado)"
    files:
      - file: "data/locales.json"
        label: "Listado de locales"
        name: "locales_list"
        format: "json"
        fields:
          - { label: "Locales", name: "", widget: "list", label_singular: "local", collapsed: false, fields: [
              {label: "Slug", name: "slug", widget: "string", hint: "minúsculas-sin-espacios"},
              {label: "Nombre", name: "nombre", widget: "string"},
              {label: "Categoría", name: "categoria", widget: "string"},
              {label: "Dirección", name: "direccion", widget: "string", required: false},
              {label: "Barrio / Ciudad", name: "barrio", widget: "string", required: false},
              {label: "Portada", name: "portada", widget: "image", required: false}
          ] }

  - name: "ajustes_globales"
    label: "Ajustes globales"
    files:
      - file: "data/ajustes.json"
        label: "Ajustes por defecto (no por local)"
        name: "ajustes_defecto"
        format: "json"
        fields:
          - { label: "WhatsApp por defecto", name: "whatsapp", widget: "string", required: false }
          - { label: "Costo de envío por defecto", name: "shipping", widget: "number", value_type: "int", required: false }

  # (Opcional) Puedes agregar más colecciones para manejar data por local si prefieres hacerlo todo desde el CMS.
